# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title/
# relative_permalinks: true

# Setup
title:               Giovani
tagline:             'Desenvolvedor'
description:         'Eae =)'
url:                 https://giovanisleite.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Giovani de Sousa Leite
  url:               https://twitter.com/queleabraco
  email:             sousa_giovani+blog@hotmail.com

github:
  repo:              https://github.com/giovanisleite/giovanisleite.github.io

# Custom vars
version:             1.0.0

plugins:
  - jekyll-paginate
